# Generated by Django 3.2.7 on 2021-09-16 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamneseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('PQ', 'PAR-Q'), ('HM', 'Histórico médico'), ('SD', 'Sintomas de doenças'), ('EV', 'estilo de vida'), ('EE', 'Expectativa de exercício'), ('IC', 'Auto imagem corporal'), ('IP', 'IPAQ')], max_length=2, verbose_name='grupo')),
                ('question', models.CharField(max_length=1000, verbose_name='perguntas')),
            ],
            options={
                'verbose_name': 'questão anamnese',
                'verbose_name_plural': 'questões anamnese',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('photoFront', models.ImageField(blank=True, null=True, upload_to='userPhotos', verbose_name='foto frontal')),
                ('photoRight', models.ImageField(blank=True, null=True, upload_to='userPhotos', verbose_name='foto direita')),
                ('photoLeft', models.ImageField(blank=True, null=True, upload_to='userPhotos', verbose_name='foto esquerda')),
                ('photoBack', models.ImageField(blank=True, null=True, upload_to='userPhotos', verbose_name='foto costas')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructorAssessment', to=settings.AUTH_USER_MODEL, verbose_name='instrutor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAssessment', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'avaliação',
                'verbose_name_plural': 'avaliações',
            },
        ),
        migrations.CreateModel(
            name='PostureQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('F', 'Frontal'), ('P', 'Posterior'), ('L', 'Lateral')], max_length=1, verbose_name='grupo')),
                ('question', models.CharField(max_length=100, verbose_name='questão')),
            ],
            options={
                'verbose_name': 'Questão postural',
                'verbose_name_plural': 'Questões posturais',
            },
        ),
        migrations.CreateModel(
            name='Skinfold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('triceps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='tríceps')),
                ('peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axiliarMedia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='axiliar media')),
                ('supraIliaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='supra ilíaca')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coxaMedial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='coxa medial')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'dobra cutânea',
                'verbose_name_plural': 'dobras cutâneas',
            },
        ),
        migrations.CreateModel(
            name='Posture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='resposta')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.posturequestion', verbose_name='questão')),
            ],
            options={
                'verbose_name': 'Postural',
                'verbose_name_plural': 'Posturais',
            },
        ),
        migrations.CreateModel(
            name='Antropometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodPressure', models.CharField(blank=True, max_length=10, null=True, verbose_name='pressao sanguinea')),
                ('oximetria', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fcRest', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='FC Repouso')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='altura')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso')),
                ('chest', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peitoral')),
                ('waist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cintura')),
                ('abdomen', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='abdômen')),
                ('hip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quadril')),
                ('leftArm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço esquerdo')),
                ('leftForearm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='antebraço esquerdo')),
                ('leftContractedArm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço esquerdo contraído')),
                ('leftThigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa esquerda')),
                ('leftCalf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha esquerda')),
                ('rightArm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço direito')),
                ('rightForearm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='antebraço direito')),
                ('rightContractedArm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço direito contraído')),
                ('rightThigh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa direita')),
                ('rightCalf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha direita')),
                ('fist', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Punho')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação')),
            ],
            options={
                'verbose_name': 'antropometria',
                'verbose_name_plural': 'antropometrias',
            },
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=50, null=True, verbose_name='resposta')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.anamnesequestion', verbose_name='questao')),
            ],
            options={
                'verbose_name': 'anamnese',
                'verbose_name_plural': 'anamneses',
            },
        ),
    ]
