# Generated by Django 3.2.7 on 2021-09-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='user',
            new_name='person',
        ),
    ]
