# Generated by Django 3.2.7 on 2021-09-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_rename_user_assessment_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação'),
        ),
        migrations.AlterField(
            model_name='posture',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='avaliação'),
        ),
    ]
