# Generated by Django 3.2.7 on 2021-09-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ('person__first_name', 'initialDate'), 'verbose_name': 'treino', 'verbose_name_plural': 'treinos'},
        ),
        migrations.RenameField(
            model_name='training',
            old_name='user',
            new_name='person',
        ),
    ]
