# Generated by Django 3.2.7 on 2021-09-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('address', models.CharField(max_length=250, verbose_name='endereço')),
                ('logo', models.IntegerField(verbose_name='logo')),
            ],
        ),
    ]
